version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13


executors:
  default:
    docker:
      - image: circleci/python:3.7.2-node


jobs:
  build:
    working_directory: ~/repo
    executor: default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Build Dist
          command: yarn build
      - save_cache:
          name: Save Dist Cache
          key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo/dist

  deploy:
    working_directory: ~/repo
    executor: default
    steps:
      - aws-cli/install
      - restore_cache:
          name: Restore Dist Cache
          key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          command: ls ~/repo
      - run:
          command: ls ~/repo/dist


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
