version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.13


executors:
  default:
    docker:
      - image: circleci/python:3.7.2-node


jobs:
  build:
    working_directory: ~/repo
    executor: default
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Run Linter
          command: yarn lint
      - run:
          name: Build Dist
          command: yarn build
      - save_cache:
          name: Save Dist Cache
          key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo/dist

  deploy:
    working_directory: ~/repo
    executor: default
    steps:
      - aws-cli/install
      - restore_cache:
          name: Restore Dist Cache
          key: v1-dist-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Sync Dist
          command: |
            aws s3 sync \
                --cache-control "no-cache" \
                --content-type "text/html" \
                --exclude "*" \
                --include "index.html" \
                --storage-class REDUCED_REDUNDANCY \
                dist s3://app.zilch.me/

            aws s3 sync \
                --cache-control "max-age=3600" \
                --content-type "text/css" \
                --delete \
                --exclude "*" \
                --include "*.css" \
                --storage-class REDUCED_REDUNDANCY \
                dist/css s3://app.zilch.me/css/

            aws s3 sync \
                --cache-control "max-age=3600" \
                --content-type "image/png" \
                --delete \
                --exclude "*" \
                --include "*.png" \
                --storage-class REDUCED_REDUNDANCY \
                dist/img s3://app.zilch.me/img/

            aws s3 sync \
                --cache-control "max-age=3600" \
                --content-type "text/javascript" \
                --delete \
                --exclude "*" \
                --include "*.js" \
                --storage-class REDUCED_REDUNDANCY \
                dist/js s3://app.zilch.me/js/

            aws s3 sync \
                --cache-control "max-age=3600" \
                --content-type "application/json" \
                --delete \
                --exclude "*" \
                --include "*.js.map" \
                --storage-class REDUCED_REDUNDANCY \
                dist/js s3://app.zilch.me/js/


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
